site_name: LiquidHub
repo_url: https://github.com/insales/insales-docs-source/

theme:
  name: 'material'

extra_css:
  - css/extra.css

extra:
  search:
    language: 'en, ru'

markdown_extensions:
  - admonition
  - codehilite
